#include QMK_KEYBOARD_H
#include "lightning.h"
#include "layer_names.h"

enum custom_keycodes {
    LAYER0 = SAFE_RANGE,
    LAYER1,
    LAYER2,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

// default
[_DEFAULT] = LAYOUT_65xt(
    KC_F13, KC_F14, KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6,     KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC, KC_DEL,

    KC_F15, KC_F16, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T,           KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_BSLS, KC_HOME,

    KC_F17, KC_F18, KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G,          KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT, KC_PGUP, 

    KC_F19, KC_F20, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B,          KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_UP, KC_PGDN,

    KC_F21, KC_F22, KC_LCTL, KC_LGUI, KC_LALT, MO(2), KC_SPC,       KC_BSPC, MO(1), KC_PSCR, KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT),

// nav layer
[_NAV] = LAYOUT_65xt(
    RGB_HUI, RGB_HUD, KC_GRV, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6,             KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_TRNS, KC_NO, 

    RGB_SAI, RGB_SAD, KC_TRNS, KC_HOME, KC_UP, KC_END, KC_PGUP, KC_NO,              QK_BOOT, EE_CLR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 

    RGB_VAI, RGB_VAD, LSFT(KC_LCTL), KC_LEFT, KC_DOWN, KC_RGHT, KC_PGDN, KC_NO,     KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, 

    RGB_TOG, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,                     KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,

    QK_BOOT, EE_CLR, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                   KC_TRNS, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO),

// symbol layer
[_SYMBOLS] = LAYOUT_65xt(
    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,      KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,

    KC_NO, KC_NO, KC_NO, KC_GRV, KC_LT, KC_GT, KC_DQUO, KC_DOT,         KC_UNDS, KC_LPRN, KC_RPRN, KC_AMPR, KC_PERC, KC_NO, KC_NO, KC_NO, KC_NO,

    KC_NO, KC_NO, KC_NO, KC_EXLM, KC_PMNS, KC_PPLS, KC_EQL, KC_HASH,    KC_COLN, KC_LCBR, KC_RCBR, KC_PIPE, KC_QUES, KC_NO, KC_NO, KC_NO,

    KC_NO, KC_NO, KC_NO, KC_CIRC, KC_PSLS, KC_PAST, KC_BSLS, KC_NO,     KC_TILD, KC_LBRC, KC_RBRC, KC_DLR, KC_AT, KC_NO, KC_NO, KC_NO, 

    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS,                KC_TRNS, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO)

};
